name: alcool_ou_gasolina
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  getwidget: ^5.0.0
  easy_localization: ^3.0.7
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
  - assets/
  - assets/translations/
