name: alcool_ou_gasolina
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    google_fonts: ^6.2.1
    getwidget: ^6.0.0
    easy_localization: ^3.0.7
    provider: ^6.1.2
    shared_preferences: ^2.5.2
    flutter_local_notifications: ^18.0.1
    timezone: ^0.10.0
    http: ^1.3.0
    url_launcher: ^6.3.1
    flutter_dotenv: ^5.2.1
    flutter_secure_storage: ^9.2.4
    flutter_svg: ^2.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/imgs/
        - assets/icons/
        - assets/translations/
        - .env
